#!/bin/sh
start() {
    sysctl -w net.netfilter.nf_conntrack_checksum=0 >/dev/null 2>&1
}
stop() {
    sysctl -w net.netfilter.nf_conntrack_checksum=1 >/dev/null 2>&1
}
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        stop
        start
        ;;
esac
exit 0
